services:
  - type: web
    name: nestjs-prisma-app
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run seed && npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: psql 'postgresql://neondb_owner:npg_AVqDh0sdC5wn@ep-dawn-forest-anmy5300-pooler.c-6.us-east-1.aws.neon.tech/sigradb?sslmode=require&channel_binding=require'
      - key: JWT_SECRET
        value: 4dm1nc3nter&s1gr4dcb4ll0s
